import type { ClassInfo, ClassProficiencyInfo, CasterProgression } from '../../types';

export const classData: Record<string, ClassInfo> = {
  'Arcanista': {
    hpBase: 8, hpPerLevel: 2, mpPerLevel: 6,
    proficiencies: 'Nenhuma',
    level1Abilities: ['Caminho do Arcanista', 'Magias (1º círculo)'],
    trainedSkills: ['misticismo', 'vontade'],
    skillChoices: [
      { count: 1, options: ['conhecimento_arcano', 'conhecimento_natureza', 'conhecimento_dungeons', 'conhecimento_plano', 'conhecimento_nobre', 'conhecimento_religioso', 'iniciativa', 'oficio', 'percepcao'] },
    ],
    abilities: [
      { level: 1, name: 'Caminho do Arcanista', description: 'Escolha um caminho arcano (Mago, Ilusionista, Necromante etc.) que define seus poderes exclusivos.' },
      { level: 1, name: 'Magias (1º círculo)', description: 'Você pode lançar magias arcanas de 1º círculo. Acessa círculos maiores a cada dois níveis.' },
      { level: 20, name: 'Arcanista Supremo', description: 'Gaste 5 PM para lançar uma magia arcana sem pagar seu custo normal.' },
    ],
  },
  'Bárbaro': {
    hpBase: 24, hpPerLevel: 6, mpPerLevel: 3,
    proficiencies: 'Armas marciais, escudos',
    level1Abilities: ['Fúria +2'],
    trainedSkills: ['fortitude', 'luta'],
    skillChoices: [
      { count: 4, options: ['adestramento', 'atletismo', 'cavalgar', 'iniciativa', 'intimidacao', 'oficio', 'percepcao', 'pontaria', 'sobrevivencia', 'vontade'] },
    ],
    abilities: [
      { level: 1, name: 'Fúria +2', description: 'Gaste 2 PM: receba +4 em ataques e dano, +ConMod PV temporários, mas sofra –5 na Defesa e não possa lançar magias. Aumenta a cada 6 níveis.' },
      { level: 3, name: 'Mente de Batalha', description: 'Enquanto em Fúria, você é imune a efeitos mentais (medo, encantamento etc.).' },
      { level: 5, name: 'Fúria +4', description: 'Bônus de ataque e dano em Fúria aumenta para +8.' },
      { level: 11, name: 'Fúria +6', description: 'Bônus de ataque e dano em Fúria aumenta para +12.' },
      { level: 17, name: 'Fúria +8', description: 'Bônus de ataque e dano em Fúria aumenta para +16.' },
      { level: 20, name: 'Bárbaro Imortal', description: 'Quando reduziria a 0 PV, pode gastar 5 PM para ficar com 1 PV. Uma vez por cena.' },
    ],
  },
  'Bardo': {
    hpBase: 12, hpPerLevel: 3, mpPerLevel: 4,
    proficiencies: 'Armas marciais',
    level1Abilities: ['Inspiração +1', 'Magias (1º círculo)'],
    trainedSkills: ['atuacao', 'reflexos'],
    skillChoices: [
      { count: 6, options: ['acrobacia', 'cavalgar', 'conhecimento_arcano', 'conhecimento_natureza', 'conhecimento_dungeons', 'conhecimento_plano', 'conhecimento_nobre', 'conhecimento_religioso', 'diplomacia', 'enganacao', 'furtividade', 'iniciativa', 'intuicao', 'investigacao', 'jogatina', 'ladinagem', 'luta', 'misticismo', 'nobreza', 'percepcao', 'pontaria', 'religiao', 'vontade'] },
    ],
    abilities: [
      { level: 1, name: 'Inspiração +1', description: 'Gaste 1 PM: um aliado em alcance curto recebe +1 em qualquer teste até o fim da cena.' },
      { level: 1, name: 'Magias (1º círculo)', description: 'Você pode lançar magias arcanas de 1º círculo.' },
      { level: 5, name: 'Inspiração +2', description: 'Bônus de Inspiração aumenta para +2.' },
      { level: 11, name: 'Inspiração +3', description: 'Bônus de Inspiração aumenta para +3.' },
      { level: 17, name: 'Inspiração +4', description: 'Bônus de Inspiração aumenta para +4.' },
      { level: 20, name: 'Obra-Prima', description: 'Uma vez por dia, você pode lançar qualquer magia arcana que conheça sem custo em PM.' },
    ],
  },
  'Bucaneiro': {
    hpBase: 16, hpPerLevel: 4, mpPerLevel: 3,
    proficiencies: 'Armas marciais',
    level1Abilities: ['Audácia', 'Insolência'],
    trainedSkills: ['reflexos'],
    skillChoices: [
      { count: 1, options: ['luta', 'pontaria'] },
      { count: 4, options: ['acrobacia', 'atletismo', 'atuacao', 'enganacao', 'fortitude', 'furtividade', 'iniciativa', 'intimidacao', 'jogatina', 'oficio', 'percepcao', 'pilotagem'] },
    ],
    abilities: [
      { level: 1, name: 'Audácia', description: 'Some seu bônus de CAR na Iniciativa. Sem armadura ou escudo pesado, some também na Defesa.' },
      { level: 1, name: 'Insolência', description: 'Gaste 1 PM: realize uma ação de movimento adicional no turno. Uma vez por rodada.' },
      { level: 6, name: 'Sortudo', description: 'Uma vez por cena, role novamente qualquer dado recém rolado e use o melhor resultado.' },
      { level: 11, name: 'Finta Aprimorada', description: 'Finta custa uma ação de movimento em vez de ação padrão.' },
      { level: 20, name: 'Pirata Lendário', description: 'Quando usa Audácia para adicionar CAR na Defesa, adiciona o dobro do modificador.' },
    ],
  },
  'Caçador': {
    hpBase: 16, hpPerLevel: 4, mpPerLevel: 4,
    proficiencies: 'Armas marciais, escudos',
    level1Abilities: ['Marca da Presa +1d4', 'Rastreador'],
    trainedSkills: ['sobrevivencia'],
    skillChoices: [
      { count: 1, options: ['luta', 'pontaria'] },
      { count: 6, options: ['adestramento', 'atletismo', 'cavalgar', 'cura', 'fortitude', 'furtividade', 'iniciativa', 'investigacao', 'oficio', 'percepcao', 'reflexos'] },
    ],
    abilities: [
      { level: 1, name: 'Marca da Presa +1d4', description: 'Gaste 1 PM: marque uma criatura. Seus ataques contra ela causam +1d4 de dano extra. A marca dura a cena.' },
      { level: 1, name: 'Rastreador', description: 'Você se move a velocidade normal ao rastrear e pode rastrear à noite sem penalidade.' },
      { level: 5, name: 'Marca da Presa +2d4', description: 'Dano de Marca da Presa aumenta para +2d4.' },
      { level: 9, name: 'Marca da Presa +3d4', description: 'Dano de Marca da Presa aumenta para +3d4.' },
      { level: 13, name: 'Marca da Presa +4d4', description: 'Dano de Marca da Presa aumenta para +4d4.' },
      { level: 17, name: 'Marca da Presa +5d4', description: 'Dano de Marca da Presa aumenta para +5d4.' },
      { level: 20, name: 'Presa Definitiva', description: 'Ao marcar uma presa, gaste 5 PM para ela não poder se tornar imune à marca e para dobrar o dano extra.' },
    ],
  },
  'Cavaleiro': {
    hpBase: 20, hpPerLevel: 5, mpPerLevel: 3,
    proficiencies: 'Armas marciais, armaduras pesadas, escudos',
    level1Abilities: ['Baluarte +2', 'Código de Honra'],
    trainedSkills: ['fortitude', 'luta'],
    skillChoices: [
      { count: 2, options: ['adestramento', 'atletismo', 'cavalgar', 'diplomacia', 'guerra', 'iniciativa', 'intimidacao', 'nobreza', 'percepcao', 'vontade'] },
    ],
    abilities: [
      { level: 1, name: 'Código de Honra', description: 'Você nunca pode atacar um alvo indefeso nem abandonar um aliado em perigo.' },
      { level: 1, name: 'Baluarte +2', description: 'Gaste 1 PM: você (e aliados adjacentes a partir do 7º nível) recebem +2 na Defesa e em testes de resistência contra efeitos sobrenaturais.' },
      { level: 2, name: 'Duelo', description: 'Gaste 2 PM: desafie um inimigo. Vocês dois recebem +1 em ataques e dano mútuos até o fim da cena.' },
      { level: 5, name: 'Caminho', description: 'Escolha entre Bastião (RD 5 quando de armadura pesada) ou Montaria (invoque uma montaria de batalha).' },
      { level: 11, name: 'Resoluto', description: 'Gaste 1 PM para rolar novamente um teste de resistência recém realizado.' },
      { level: 20, name: 'Bravura Final', description: 'Ao chegar a 0 PV, pode gastar 5 PM por turno para permanecer consciente e continuar agindo.' },
    ],
  },
  'Clérigo': {
    hpBase: 16, hpPerLevel: 4, mpPerLevel: 5,
    proficiencies: 'Armaduras pesadas, escudos',
    level1Abilities: ['Devoto', 'Magias (1º círculo)'],
    trainedSkills: ['religiao', 'vontade'],
    skillChoices: [
      { count: 2, options: ['conhecimento_arcano', 'conhecimento_natureza', 'conhecimento_dungeons', 'conhecimento_plano', 'conhecimento_nobre', 'conhecimento_religioso', 'cura', 'diplomacia', 'fortitude', 'iniciativa', 'intuicao', 'luta', 'misticismo', 'nobreza', 'oficio', 'percepcao'] },
    ],
    abilities: [
      { level: 1, name: 'Devoto', description: 'Você serve a uma divindade, seguindo suas obrigações e restrições em troca de Poderes Concedidos.' },
      { level: 1, name: 'Magias (1º círculo)', description: 'Você lança magias divinas de 1º círculo. Acessa círculos maiores a cada dois níveis.' },
      { level: 20, name: 'Mão da Divindade', description: 'Gaste 15 PM para lançar três magias divinas como ações livres no mesmo turno.' },
    ],
  },
  'Druida': {
    hpBase: 16, hpPerLevel: 4, mpPerLevel: 4,
    proficiencies: 'Escudos',
    level1Abilities: ['Devoto', 'Empatia Selvagem', 'Magias (1º círculo)'],
    trainedSkills: ['sobrevivencia', 'vontade'],
    skillChoices: [
      { count: 4, options: ['adestramento', 'atletismo', 'cavalgar', 'conhecimento_arcano', 'conhecimento_natureza', 'conhecimento_dungeons', 'conhecimento_plano', 'conhecimento_nobre', 'conhecimento_religioso', 'cura', 'fortitude', 'iniciativa', 'intuicao', 'luta', 'misticismo', 'oficio', 'percepcao', 'religiao'] },
    ],
    abilities: [
      { level: 1, name: 'Devoto', description: 'Você serve a uma divindade da natureza (geralmente Allihanna), seguindo suas obrigações em troca de Poderes Concedidos.' },
      { level: 1, name: 'Empatia Selvagem', description: 'Você pode se comunicar com animais. Com um teste de Adestramento, pode calmá-los ou pedir ajuda simples.' },
      { level: 1, name: 'Magias (1º círculo)', description: 'Você lança magias divinas de 1º círculo.' },
      { level: 2, name: 'Caminho dos Ermos', description: 'Você se move normalmente por terreno difícil natural e a CD para rastrear você aumenta em +10.' },
      { level: 20, name: 'Força da Natureza', description: 'Todas as suas magias custam –2 PM e têm CD +2. Em terreno natural, esses bônus dobram.' },
    ],
  },
  'Guerreiro': {
    hpBase: 20, hpPerLevel: 5, mpPerLevel: 3,
    proficiencies: 'Armas marciais, armaduras pesadas, escudos',
    level1Abilities: ['Ataque Especial +4'],
    trainedSkills: ['fortitude'],
    skillChoices: [
      { count: 1, options: ['luta', 'pontaria'] },
      { count: 2, options: ['adestramento', 'atletismo', 'cavalgar', 'guerra', 'iniciativa', 'intimidacao', 'oficio', 'percepcao', 'reflexos'] },
    ],
    abilities: [
      { level: 1, name: 'Ataque Especial +4', description: 'Gaste 1 PM: receba +4 em testes de ataque ou rolagens de dano (escolha antes de rolar). A cada 4 níveis, gaste +1 PM para +4 adicionais.' },
      { level: 3, name: 'Durão', description: 'Gaste 2 PM quando sofrer dano: reduza o dano à metade.' },
      { level: 6, name: 'Ataque Extra', description: 'Gaste 2 PM ao usar a ação atacar para realizar um ataque adicional com a mesma arma.' },
      { level: 20, name: 'Campeão', description: 'Dano de todos os seus ataques aumenta um passo. Acertando um Ataque Especial ou Golpe Pessoal, recupera metade dos PM gastos.' },
    ],
  },
  'Inventor': {
    hpBase: 12, hpPerLevel: 3, mpPerLevel: 4,
    proficiencies: 'Nenhuma',
    level1Abilities: ['Engenhosidade', 'Protótipo'],
    trainedSkills: ['oficio', 'vontade'],
    skillChoices: [
      { count: 4, options: ['conhecimento_arcano', 'conhecimento_natureza', 'conhecimento_dungeons', 'conhecimento_plano', 'conhecimento_nobre', 'conhecimento_religioso', 'cura', 'diplomacia', 'fortitude', 'iniciativa', 'investigacao', 'luta', 'misticismo', 'percepcao', 'pilotagem', 'pontaria'] },
    ],
    abilities: [
      { level: 1, name: 'Engenhosidade', description: 'Gaste 2 PM ao fazer um teste de perícia: receba bônus igual ao modificador de INT. Não funciona em testes de ataque.' },
      { level: 1, name: 'Protótipo', description: 'Você começa com um item superior com uma modificação ou 10 itens alquímicos (até T$ 500).' },
      { level: 2, name: 'Fabricar Item Superior (1 mod)', description: 'Você pode fabricar itens superiores com uma modificação.' },
      { level: 3, name: 'Comerciante', description: 'Você vende itens 10% mais caro (não cumulativo com Barganha).' },
      { level: 7, name: 'Encontrar Fraqueza', description: 'Gaste 2 PM + ação de movimento: ignore a RD de um objeto ou receba +2 em ataques contra alvo de armadura ou construto.' },
      { level: 9, name: 'Fabricar Item Mágico (menor)', description: 'Você recebe e pode fabricar itens mágicos menores.' },
      { level: 11, name: 'Olho do Dragão', description: 'Gaste uma ação completa para analisar um item e descobrir automaticamente se é mágico e suas propriedades.' },
      { level: 13, name: 'Fabricar Item Mágico (médio)', description: 'Você pode fabricar itens mágicos médios.' },
      { level: 17, name: 'Fabricar Item Mágico (maior)', description: 'Você pode fabricar itens mágicos maiores.' },
      { level: 20, name: 'Obra-Prima', description: 'Você cria um item lendário único, aprovado pelo mestre, equivalente a item superior (6 mods) + item mágico maior.' },
    ],
  },
  'Ladino': {
    hpBase: 12, hpPerLevel: 3, mpPerLevel: 4,
    proficiencies: 'Nenhuma',
    level1Abilities: ['Ataque Furtivo +1d6', 'Especialista'],
    trainedSkills: ['ladinagem', 'reflexos'],
    skillChoices: [
      { count: 8, options: ['acrobacia', 'atletismo', 'atuacao', 'cavalgar', 'conhecimento_arcano', 'conhecimento_natureza', 'conhecimento_dungeons', 'conhecimento_plano', 'conhecimento_nobre', 'conhecimento_religioso', 'diplomacia', 'enganacao', 'furtividade', 'iniciativa', 'intimidacao', 'intuicao', 'investigacao', 'jogatina', 'luta', 'oficio', 'percepcao', 'pilotagem', 'pontaria'] },
    ],
    abilities: [
      { level: 1, name: 'Ataque Furtivo +1d6', description: 'Uma vez por rodada, quando atinge um alvo desprevenido ou flanqueado, cause +1d6 de dano extra. Aumenta +1d6 a cada dois níveis.' },
      { level: 1, name: 'Especialista', description: 'Escolha perícias treinadas (igual ao bônus de INT): ao usá-las, gaste 1 PM para dobrar o bônus de treinamento.' },
      { level: 2, name: 'Evasão', description: 'Em ataques que permitam Reflexos para reduzir dano à metade: se passar, não sofre dano algum.' },
      { level: 4, name: 'Esquiva Sobrenatural', description: 'Seus instintos estão tão aguçados que você nunca fica surpreendido.' },
      { level: 8, name: 'Olhos nas Costas', description: 'Você não pode ser flanqueado.' },
      { level: 10, name: 'Evasão Aprimorada', description: 'Em ataques com Reflexos: sem dano se passar, metade do dano se falhar.' },
      { level: 20, name: 'A Pessoa Certa para o Trabalho', description: 'Gaste 5 PM ao fazer um ataque furtivo ou usar uma perícia de ladino: receba +10 no teste.' },
    ],
  },
  'Lutador': {
    hpBase: 20, hpPerLevel: 5, mpPerLevel: 3,
    proficiencies: 'Nenhuma',
    level1Abilities: ['Briga (1d6)', 'Golpe Relâmpago'],
    trainedSkills: ['fortitude', 'luta'],
    skillChoices: [
      { count: 4, options: ['acrobacia', 'adestramento', 'atletismo', 'enganacao', 'furtividade', 'iniciativa', 'intimidacao', 'oficio', 'percepcao', 'pontaria', 'reflexos'] },
    ],
    abilities: [
      { level: 1, name: 'Briga (1d6)', description: 'Seus ataques desarmados causam 1d6 de dano e podem ser letais ou não letais sem penalidade.' },
      { level: 1, name: 'Golpe Relâmpago', description: 'Ao usar a ação atacar desarmado, gaste 1 PM para realizar um ataque desarmado adicional.' },
      { level: 3, name: 'Casca Grossa', description: 'Some seu bônus de CON na Defesa (limitado pelo nível) sem armadura pesada. A cada 4 níveis, recebe +1 na Defesa.' },
      { level: 5, name: 'Briga (1d8) + Golpe Cruel', description: 'Dano desarmado aumenta para 1d8. Margem de ameaça com ataques desarmados aumenta em +1.' },
      { level: 9, name: 'Briga (1d10) + Golpe Violento', description: 'Dano desarmado aumenta para 1d10. Multiplicador de crítico com ataques desarmados aumenta em +1.' },
      { level: 13, name: 'Briga (2d6)', description: 'Dano desarmado aumenta para 2d6.' },
      { level: 17, name: 'Briga (2d8)', description: 'Dano desarmado aumenta para 2d8.' },
      { level: 20, name: 'Dono da Rua (2d10)', description: 'Dano desarmado aumenta para 2d10. Ao atacar desarmado, você pode fazer dois ataques em vez de um (Golpe Relâmpago adiciona um terceiro).' },
    ],
  },
  'Nobre': {
    hpBase: 16, hpPerLevel: 4, mpPerLevel: 4,
    proficiencies: 'Armas marciais, armaduras pesadas, escudos',
    level1Abilities: ['Autoconfiança', 'Espólio', 'Orgulho'],
    trainedSkills: ['vontade'],
    skillChoices: [
      { count: 1, options: ['diplomacia', 'intimidacao'] },
      { count: 4, options: ['adestramento', 'atuacao', 'cavalgar', 'conhecimento_arcano', 'conhecimento_natureza', 'conhecimento_dungeons', 'conhecimento_plano', 'conhecimento_nobre', 'conhecimento_religioso', 'enganacao', 'fortitude', 'guerra', 'iniciativa', 'intuicao', 'investigacao', 'jogatina', 'luta', 'nobreza', 'oficio', 'percepcao', 'pontaria'] },
    ],
    abilities: [
      { level: 1, name: 'Autoconfiança', description: 'Some seu bônus de CAR em vez de DES na Defesa (exceto de armadura pesada).' },
      { level: 1, name: 'Espólio', description: 'Você recebe um item a sua escolha com preço de até T$ 2.000.' },
      { level: 1, name: 'Orgulho', description: 'Ao fazer um teste de perícia, gaste PM (limitado pelo bônus de CAR): receba +2 por PM gasto no teste.' },
      { level: 2, name: 'Riqueza', description: 'Uma vez por aventura, faça um teste de CAR + nível de nobre para receber esse valor em Tibares de ouro.' },
      { level: 3, name: 'Gritar Ordens', description: 'Gaste PM (limitado pelo bônus de CAR): aliados em alcance curto recebem bônus igual aos PM gastos em todos os testes de perícia até seu próximo turno.' },
      { level: 20, name: 'Realeza', description: 'Criaturas que falhem em 10+ no teste de Presença Aristocrática passam a lutar ao seu lado. Alvos reduzidos a 0 PV por Palavras Afiadas também se rendem.' },
    ],
  },
  'Paladino': {
    hpBase: 20, hpPerLevel: 5, mpPerLevel: 3,
    proficiencies: 'Armas marciais, armaduras pesadas, escudos',
    level1Abilities: ['Abençoado', 'Código do Herói', 'Golpe Divino (+1d8)'],
    trainedSkills: ['luta', 'vontade'],
    skillChoices: [
      { count: 2, options: ['adestramento', 'atletismo', 'cavalgar', 'cura', 'diplomacia', 'fortitude', 'guerra', 'iniciativa', 'intuicao', 'nobreza', 'percepcao', 'religiao'] },
    ],
    abilities: [
      { level: 1, name: 'Abençoado', description: 'Some seu bônus de CAR ao total de PM. Torne-se devoto de uma divindade bondosa e ganhe seus Poderes Concedidos.' },
      { level: 1, name: 'Código do Herói', description: 'Sempre mantenha sua palavra, nunca recuse ajuda a inocentes e jamais minta, trapaceie ou roube. Violar o código remove todos os seus PM até o dia seguinte.' },
      { level: 1, name: 'Golpe Divino (+1d8)', description: 'Gaste 2 PM ao atacar corpo a corpo: some CAR no teste de ataque e +1d8 no dano. A cada 4 níveis, gaste +1 PM para +1d8 extra.' },
      { level: 2, name: 'Cura pelas Mãos (1d8+1)', description: 'Gaste 1 PM + ação de movimento: cure 1d8+1 PV de um alvo em alcance corpo a corpo. Escala a cada 4 níveis.' },
      { level: 3, name: 'Aura Sagrada', description: 'Gaste 1 PM para ativar uma aura (alcance curto) que ilumina como tocha e dá aos aliados bônus de CAR em testes de resistência. Custo: 1 PM/turno.' },
      { level: 5, name: 'Bênção da Justiça', description: 'Escolha Égide Sagrada (bônus de CAR na Defesa para aliados adjacentes) ou Montaria Sagrada (invocar montaria divina).' },
      { level: 9, name: 'Golpe Divino (+3d8)', description: 'Golpe Divino pode causar até +3d8 de dano (gaste 2+2 PM).' },
      { level: 13, name: 'Golpe Divino (+4d8)', description: 'Golpe Divino pode causar até +4d8 de dano.' },
      { level: 17, name: 'Golpe Divino (+5d8)', description: 'Golpe Divino pode causar até +5d8 de dano.' },
      { level: 20, name: 'Vingador Sagrado', description: 'Gaste 10 PM + ação completa: voo 18m, RD 20 e some CAR em ataques e dano corpo a corpo até o fim da cena.' },
    ],
  },
  'Miragem': {
    hpBase: 16, hpPerLevel: 4, mpPerLevel: 3,
    proficiencies: 'Armas marciais, escudos',
    level1Abilities: ['Dança da Areia', 'Movimento Furtivo'],
    trainedSkills: ['furtividade', 'iniciativa'],
    skillChoices: [
      { count: 4, options: ['acrobacia', 'atletismo', 'cavalgar', 'enganacao', 'fortitude', 'luta', 'percepcao', 'pontaria', 'reflexos', 'sobrevivencia'] },
    ],
    abilities: [
      { level: 1, name: 'Dança da Areia', description: 'Ao se mover ao menos 3m antes de atacar, você recebe +2 no teste de ataque e +1d6 no dano. Você pode usar Furtividade para se esconder mesmo sem cobertura após atacar.' },
      { level: 1, name: 'Movimento Furtivo', description: 'Você pode se mover com sua velocidade completa ao fazer testes de Furtividade sem penalidade.' },
      { level: 3, name: 'Investida Acrobática', description: 'Você pode fazer uma investida como ação de movimento, e não precisa se mover em linha reta ao investir.' },
      { level: 5, name: 'Cortina de Poeira', description: 'Gaste 2 PM: cria cortina de areia em alcance curto. Criaturas na área ficam camufladas e têm Vontade CD Des testada para agir normalmente.' },
      { level: 7, name: 'Guerrilheiro das Dunas', description: 'Você recebe +2 em testes de ataque e na Defesa quando não estiver adjacente a nenhum aliado.' },
      { level: 9, name: 'Mergulho Terrestre', description: 'Gaste 3 PM: você se submerge na areia ou solo solto e pode se mover até 6m por rodada abaixo da superfície. Reemerge como ação de movimento.' },
      { level: 20, name: 'Corpo de Areia', description: 'Gaste 5 PM: por uma cena você se torna imune a dano físico e pode atravessar criaturas e objetos. Qualquer ataque seu durante este estado causa +4d6 de dano.' },
    ],
  },
  'Místico': {
    hpBase: 16, hpPerLevel: 4, mpPerLevel: 4,
    proficiencies: 'Armas marciais',
    level1Abilities: ['Afinidade Elemental', 'Ataque Elemental', 'Magias (1º círculo)'],
    trainedSkills: ['misticismo', 'vontade'],
    skillChoices: [
      { count: 4, options: ['atletismo', 'conhecimento_arcano', 'conhecimento_natureza', 'conhecimento_plano', 'fortitude', 'intuicao', 'luta', 'percepcao', 'reflexos', 'sobrevivencia'] },
    ],
    abilities: [
      { level: 1, name: 'Afinidade Elemental', description: 'Escolha um elemento (ar, água, fogo ou terra). Você recebe resistência 5 ao dano desse elemento e seus ataques e magias podem causar dano desse tipo.' },
      { level: 1, name: 'Ataque Elemental', description: 'Uma vez por rodada, pode gastar 1 PM para que seu ataque cause dano adicional de seu elemento (1d6 + metade do nível).' },
      { level: 1, name: 'Magias (1º círculo)', description: 'Você pode lançar magias arcanas de 1º círculo. Acessa círculos maiores a cada quatro níveis.' },
      { level: 2, name: 'Língua Primordial', description: 'Você aprende e passa a falar a língua dos elementais e pode se comunicar com elementais e criaturas do plano correspondente ao seu elemento.' },
      { level: 3, name: 'Tradição Oral', description: 'Uma vez por descanso longo, você pode recuperar PM adicionais iguais ao seu nível ao meditar sobre os ensinamentos de um mestre elemental.' },
      { level: 4, name: 'Sexto Sentido', description: 'Você detecta automaticamente elementais e criaturas do seu elemento em alcance médio, mesmo sem vê-los. Recebe +2 em Percepção e Iniciativa.' },
      { level: 6, name: 'Afinidade Evoluída', description: 'Sua resistência elemental aumenta para 10 e você passa a ser imune às condições adversas do seu elemento (congelamento, queimaduras, sufocamento, esmagamento).' },
      { level: 20, name: 'Comunhão Suprema', description: 'Gaste 5 PM: por cena você se torna um elemental do seu tipo. Recebe as imunidades, deslocamentos e ataques naturais de um elemental grande.' },
    ],
  },
  'Samurai': {
    hpBase: 20, hpPerLevel: 5, mpPerLevel: 3,
    proficiencies: 'Armas marciais, armaduras pesadas',
    level1Abilities: ['Arma Ancestral', 'Código do Samurai', 'Grito de Kiai'],
    trainedSkills: ['fortitude', 'luta'],
    skillChoices: [
      { count: 3, options: ['atletismo', 'cavalgar', 'guerra', 'iniciativa', 'intimidacao', 'intuicao', 'nobreza', 'percepcao', 'vontade'] },
    ],
    abilities: [
      { level: 1, name: 'Arma Ancestral', description: 'Você possui uma arma ancestral (katana ou outra arma marcial). Ela é considerada mágica e recebe +1 em ataque e dano por cada 5 níveis de personagem.' },
      { level: 1, name: 'Código do Samurai', description: 'Enquanto seguir seu código de honra, você recebe +2 em todos os testes de resistência e +1 na Defesa. Se violar o código, perde esses bônus até ser redimido.' },
      { level: 1, name: 'Grito de Kiai', description: 'Gaste 1 PM: seu próximo ataque neste turno causa dano máximo. Pode ser usado uma vez por cena sem custo adicional de PM.' },
      { level: 3, name: 'Olhar Assustador', description: 'Gaste 1 PM: um olhar carregado de poder intimida criaturas em alcance curto. Cada criatura deve passar em Vontade (CD Car) ou ficar abalada por 1 rodada.' },
      { level: 10, name: 'Arma Espiritual', description: 'Sua arma ancestral desenvolve vontade própria. Ela não pode ser desarmada involuntariamente e retorna à sua mão como ação livre. Causa +2d6 de dano extra contra criaturas de alinhamento oposto.' },
      { level: 20, name: 'Shogun', description: 'Você se torna um lorde de guerra lendário. Recebe +4 em Força e Constituição, imunidade a medo e seus aliados em alcance médio recebem +2 em testes de ataque e resistência.' },
    ],
  },
};

export const classMagicType: Record<string, 'arcana' | 'divina' | null> = {
  'Arcanista': 'arcana', 'Bardo': 'arcana', 'Místico': 'arcana',
  'Clérigo': 'divina', 'Druida': 'divina',
  'Bárbaro': null, 'Bucaneiro': null, 'Caçador': null,
  'Cavaleiro': null, 'Guerreiro': null, 'Inventor': null,
  'Ladino': null, 'Lutador': null, 'Miragem': null, 'Nobre': null,
  'Paladino': null, 'Samurai': null,
};

export const classStartingSpells: Record<string, number> = {
  'Arcanista': 3, 'Bardo': 2, 'Clérigo': 3, 'Druida': 2, 'Místico': 2,
};

export const classPaths: Record<string, string[]> = {
  'Arcanista': ['Mago', 'Ilusionista', 'Necromante', 'Conjurador', 'Elementalista', 'Bruxo'],
};

export const classProficiencies: Record<string, ClassProficiencyInfo> = {
  'Arcanista':  { martialWeapons: false, heavyArmor: false, shields: false },
  'Bárbaro':    { martialWeapons: true,  heavyArmor: false, shields: true  },
  'Bardo':      { martialWeapons: true,  heavyArmor: false, shields: false },
  'Bucaneiro':  { martialWeapons: true,  heavyArmor: false, shields: false },
  'Caçador':    { martialWeapons: true,  heavyArmor: false, shields: true  },
  'Cavaleiro':  { martialWeapons: true,  heavyArmor: true,  shields: true  },
  'Clérigo':    { martialWeapons: false, heavyArmor: true,  shields: true  },
  'Druida':     { martialWeapons: false, heavyArmor: false, shields: true  },
  'Guerreiro':  { martialWeapons: true,  heavyArmor: true,  shields: true  },
  'Inventor':   { martialWeapons: false, heavyArmor: false, shields: false },
  'Ladino':     { martialWeapons: false, heavyArmor: false, shields: false },
  'Lutador':    { martialWeapons: false, heavyArmor: false, shields: false },
  'Miragem':    { martialWeapons: true,  heavyArmor: false, shields: true  },
  'Místico':    { martialWeapons: true,  heavyArmor: false, shields: false },
  'Nobre':      { martialWeapons: true,  heavyArmor: true,  shields: true  },
  'Paladino':   { martialWeapons: true,  heavyArmor: true,  shields: true  },
  'Samurai':    { martialWeapons: true,  heavyArmor: true,  shields: false },
};

// Tabelas de progressão das 14 classes (nível 1..20). Fonte: Classes.pdf Tabelas 1-4..1-17.
// Cada entrada é a string de habilidades daquele nível (pode conter vírgulas).
export const classProgression: Record<string, string[][]> = {
  'Arcanista': [
    ['Caminho do arcanista', 'Magias (1º círculo)'],
    ['Poder de arcanista'],
    ['Poder de arcanista'],
    ['Poder de arcanista'],
    ['Magias (2º círculo)', 'Poder de arcanista'],
    ['Poder de arcanista'],
    ['Poder de arcanista'],
    ['Poder de arcanista'],
    ['Magias (3º círculo)', 'Poder de arcanista'],
    ['Poder de arcanista'],
    ['Poder de arcanista'],
    ['Poder de arcanista'],
    ['Magias (4º círculo)', 'Poder de arcanista'],
    ['Poder de arcanista'],
    ['Poder de arcanista'],
    ['Poder de arcanista'],
    ['Magias (5º círculo)', 'Poder de arcanista'],
    ['Poder de arcanista'],
    ['Poder de arcanista'],
    ['Alta arcana', 'Poder de arcanista'],
  ],
  'Bárbaro': [
    ['Fúria +2'],
    ['Poder de bárbaro'],
    ['Instinto selvagem +1', 'Poder de bárbaro'],
    ['Poder de bárbaro'],
    ['Poder de bárbaro', 'Resistência a dano 2'],
    ['Fúria +3', 'Poder de bárbaro'],
    ['Poder de bárbaro'],
    ['Poder de bárbaro', 'Resistência a dano 4'],
    ['Instinto selvagem +2', 'Poder de bárbaro'],
    ['Poder de bárbaro'],
    ['Fúria +4', 'Poder de bárbaro', 'Resistência a dano 6'],
    ['Poder de bárbaro'],
    ['Poder de bárbaro'],
    ['Poder de bárbaro', 'Resistência a dano 8'],
    ['Instinto selvagem +3', 'Poder de bárbaro'],
    ['Fúria +5', 'Poder de bárbaro'],
    ['Poder de bárbaro', 'Resistência a dano 10'],
    ['Poder de bárbaro'],
    ['Poder de bárbaro'],
    ['Fúria titânica', 'Poder de bárbaro'],
  ],
  'Bardo': [
    ['Inspiração +1', 'Magias (1º círculo)'],
    ['Poder de bardo', 'Eclético'],
    ['Poder de bardo'],
    ['Poder de bardo'],
    ['Inspiração +2', 'Poder de bardo'],
    ['Magias (2º círculo)', 'Poder de bardo'],
    ['Poder de bardo'],
    ['Poder de bardo'],
    ['Inspiração +3', 'Poder de bardo'],
    ['Magias (3º círculo)', 'Poder de bardo'],
    ['Poder de bardo'],
    ['Poder de bardo'],
    ['Inspiração +4', 'Poder de bardo'],
    ['Magias (4º círculo)', 'Poder de bardo'],
    ['Poder de bardo'],
    ['Poder de bardo'],
    ['Inspiração +5', 'Poder de bardo'],
    ['Poder de bardo'],
    ['Poder de bardo'],
    ['Artista completo', 'Poder de bardo'],
  ],
  'Bucaneiro': [
    ['Audácia', 'Insolência'],
    ['Evasão', 'Poder de bucaneiro'],
    ['Esquiva sagaz +1', 'Poder de bucaneiro'],
    ['Poder de bucaneiro'],
    ['Panache', 'Poder de bucaneiro'],
    ['Poder de bucaneiro'],
    ['Esquiva sagaz +2', 'Poder de bucaneiro'],
    ['Poder de bucaneiro'],
    ['Poder de bucaneiro'],
    ['Evasão aprimorada', 'Poder de bucaneiro'],
    ['Esquiva sagaz +3', 'Poder de bucaneiro'],
    ['Poder de bucaneiro'],
    ['Poder de bucaneiro'],
    ['Poder de bucaneiro'],
    ['Esquiva sagaz +4', 'Poder de bucaneiro'],
    ['Poder de bucaneiro'],
    ['Poder de bucaneiro'],
    ['Poder de bucaneiro'],
    ['Esquiva sagaz +5', 'Poder de bucaneiro'],
    ['Poder de bucaneiro', 'Sorte de Nimb'],
  ],
  'Caçador': [
    ['Marca da presa +1d4', 'Rastreador'],
    ['Poder de caçador'],
    ['Explorador', 'Poder de caçador'],
    ['Poder de caçador'],
    ['Caminho do explorador', 'Marca da presa +1d8', 'Poder de caçador'],
    ['Poder de caçador'],
    ['Explorador', 'Poder de caçador'],
    ['Poder de caçador'],
    ['Marca da presa +1d12', 'Poder de caçador'],
    ['Poder de caçador'],
    ['Explorador', 'Poder de caçador'],
    ['Poder de caçador'],
    ['Marca da presa +2d8', 'Poder de caçador'],
    ['Poder de caçador'],
    ['Explorador', 'Poder de caçador'],
    ['Poder de caçador'],
    ['Marca da presa +2d10', 'Poder de caçador'],
    ['Poder de caçador'],
    ['Explorador', 'Poder de caçador'],
    ['Mestre caçador', 'Poder de caçador'],
  ],
  'Cavaleiro': [
    ['Baluarte +2', 'Código de honra'],
    ['Duelo', 'Poder de cavaleiro'],
    ['Poder de cavaleiro'],
    ['Poder de cavaleiro'],
    ['Caminho do cavaleiro', 'Baluarte +4', 'Poder de cavaleiro'],
    ['Poder de cavaleiro'],
    ['Baluarte (aliados adjacentes)', 'Poder de cavaleiro'],
    ['Poder de cavaleiro'],
    ['Baluarte +6', 'Poder de cavaleiro'],
    ['Poder de cavaleiro'],
    ['Poder de cavaleiro', 'Resoluto'],
    ['Poder de cavaleiro'],
    ['Baluarte +8', 'Poder de cavaleiro'],
    ['Poder de cavaleiro'],
    ['Baluarte (aliados em alcance curto)', 'Poder de cavaleiro'],
    ['Poder de cavaleiro'],
    ['Baluarte +10', 'Poder de cavaleiro'],
    ['Poder de cavaleiro'],
    ['Poder de cavaleiro'],
    ['Bravura final', 'Poder de cavaleiro'],
  ],
  'Clérigo': [
    ['Devoto', 'Magias (1º círculo)'],
    ['Poder de clérigo'],
    ['Poder de clérigo'],
    ['Poder de clérigo'],
    ['Magias (2º círculo)', 'Poder de clérigo'],
    ['Poder de clérigo'],
    ['Poder de clérigo'],
    ['Poder de clérigo'],
    ['Magias (3º círculo)', 'Poder de clérigo'],
    ['Poder de clérigo'],
    ['Poder de clérigo'],
    ['Poder de clérigo'],
    ['Magias (4º círculo)', 'Poder de clérigo'],
    ['Poder de clérigo'],
    ['Poder de clérigo'],
    ['Poder de clérigo'],
    ['Magias (5º círculo)', 'Poder de clérigo'],
    ['Poder de clérigo'],
    ['Poder de clérigo'],
    ['Mão da divindade', 'Poder de clérigo'],
  ],
  'Druida': [
    ['Devoto', 'Empatia selvagem', 'Magias (1º círculo)'],
    ['Caminho dos ermos', 'Poder de druida'],
    ['Poder de druida'],
    ['Poder de druida'],
    ['Poder de druida'],
    ['Magias (2º círculo)', 'Poder de druida'],
    ['Poder de druida'],
    ['Poder de druida'],
    ['Poder de druida'],
    ['Magias (3º círculo)', 'Poder de druida'],
    ['Poder de druida'],
    ['Poder de druida'],
    ['Poder de druida'],
    ['Magias (4º círculo)', 'Poder de druida'],
    ['Poder de druida'],
    ['Poder de druida'],
    ['Poder de druida'],
    ['Poder de druida'],
    ['Poder de druida'],
    ['Força da natureza', 'Poder de druida'],
  ],
  'Guerreiro': [
    ['Ataque especial +4'],
    ['Poder de guerreiro'],
    ['Durão', 'Poder de guerreiro'],
    ['Poder de guerreiro'],
    ['Ataque especial +8', 'Poder de guerreiro'],
    ['Ataque extra', 'Poder de guerreiro'],
    ['Poder de guerreiro'],
    ['Poder de guerreiro'],
    ['Ataque especial +12', 'Poder de guerreiro'],
    ['Poder de guerreiro'],
    ['Poder de guerreiro'],
    ['Poder de guerreiro'],
    ['Ataque especial +16', 'Poder de guerreiro'],
    ['Poder de guerreiro'],
    ['Poder de guerreiro'],
    ['Poder de guerreiro'],
    ['Ataque especial +20', 'Poder de guerreiro'],
    ['Poder de guerreiro'],
    ['Poder de guerreiro'],
    ['Campeão', 'Poder de guerreiro'],
  ],
  'Inventor': [
    ['Engenhosidade', 'Protótipo'],
    ['Fabricar item superior (1 modificação)', 'Poder de inventor'],
    ['Comerciante', 'Poder de inventor'],
    ['Fabricar item superior (2 modificações)', 'Poder de inventor'],
    ['Poder de inventor'],
    ['Fabricar item superior (3 modificações)', 'Poder de inventor'],
    ['Encontrar fraqueza', 'Poder de inventor'],
    ['Fabricar item superior (4 modificações)', 'Poder de inventor'],
    ['Fabricar item mágico (menor)', 'Poder de inventor'],
    ['Fabricar item superior (5 modificações)', 'Poder de inventor'],
    ['Olho do dragão', 'Poder de inventor'],
    ['Fabricar item superior (6 modificações)', 'Poder de inventor'],
    ['Fabricar item mágico (médio)', 'Poder de inventor'],
    ['Poder de inventor'],
    ['Poder de inventor'],
    ['Poder de inventor'],
    ['Fabricar item mágico (maior)', 'Poder de inventor'],
    ['Poder de inventor'],
    ['Poder de inventor'],
    ['Obra-prima', 'Poder de inventor'],
  ],
  'Ladino': [
    ['Ataque furtivo +1d6', 'Especialista'],
    ['Evasão', 'Poder de ladino'],
    ['Ataque furtivo +2d6', 'Poder de ladino'],
    ['Esquiva sobrenatural', 'Poder de ladino'],
    ['Ataque furtivo +3d6', 'Poder de ladino'],
    ['Poder de ladino'],
    ['Ataque furtivo +4d6', 'Poder de ladino'],
    ['Olhos nas costas', 'Poder de ladino'],
    ['Ataque furtivo +5d6', 'Poder de ladino'],
    ['Evasão aprimorada', 'Poder de ladino'],
    ['Ataque furtivo +6d6', 'Poder de ladino'],
    ['Poder de ladino'],
    ['Ataque furtivo +7d6', 'Poder de ladino'],
    ['Poder de ladino'],
    ['Ataque furtivo +8d6', 'Poder de ladino'],
    ['Poder de ladino'],
    ['Ataque furtivo +9d6', 'Poder de ladino'],
    ['Poder de ladino'],
    ['Ataque furtivo +10d6', 'Poder de ladino'],
    ['A pessoa certa para o trabalho', 'Poder de ladino'],
  ],
  'Lutador': [
    ['Briga (1d6)', 'Golpe relâmpago'],
    ['Poder de lutador'],
    ['Casca grossa (Con)', 'Poder de lutador'],
    ['Poder de lutador'],
    ['Briga (1d8)', 'Golpe cruel', 'Poder de lutador'],
    ['Poder de lutador'],
    ['Casca grossa (Con+1)', 'Poder de lutador'],
    ['Poder de lutador'],
    ['Briga (1d10)', 'Golpe violento', 'Poder de lutador'],
    ['Poder de lutador'],
    ['Casca grossa (Con+2)', 'Poder de lutador'],
    ['Poder de lutador'],
    ['Briga (2d6)', 'Poder de lutador'],
    ['Poder de lutador'],
    ['Casca grossa (Con+3)', 'Poder de lutador'],
    ['Poder de lutador'],
    ['Briga (2d8)', 'Poder de lutador'],
    ['Poder de lutador'],
    ['Casca grossa (Con+4)', 'Poder de lutador'],
    ['Dono da rua (2d10)', 'Poder de lutador'],
  ],
  'Nobre': [
    ['Autoconfiança', 'Espólio', 'Orgulho'],
    ['Poder de nobre', 'Riqueza'],
    ['Gritar ordens', 'Poder de nobre'],
    ['Poder de nobre'],
    ['Poder de nobre'],
    ['Poder de nobre'],
    ['Poder de nobre'],
    ['Poder de nobre'],
    ['Poder de nobre'],
    ['Poder de nobre'],
    ['Poder de nobre'],
    ['Poder de nobre'],
    ['Poder de nobre'],
    ['Poder de nobre'],
    ['Poder de nobre'],
    ['Poder de nobre'],
    ['Poder de nobre'],
    ['Poder de nobre'],
    ['Poder de nobre'],
    ['Realeza', 'Poder de nobre'],
  ],
  'Paladino': [
    ['Abençoado', 'Código do herói', 'Golpe divino (+1d8)'],
    ['Cura pelas mãos (1d8+1 PV)', 'Poder de paladino'],
    ['Aura sagrada', 'Poder de paladino'],
    ['Poder de paladino'],
    ['Bênção da justiça', 'Golpe divino (+2d8)', 'Poder de paladino'],
    ['Cura pelas mãos (2d8+2 PV)', 'Poder de paladino'],
    ['Poder de paladino'],
    ['Poder de paladino'],
    ['Golpe divino (+3d8)', 'Poder de paladino'],
    ['Cura pelas mãos (3d8+3 PV)', 'Poder de paladino'],
    ['Poder de paladino'],
    ['Poder de paladino'],
    ['Golpe divino (+4d8)', 'Poder de paladino'],
    ['Cura pelas mãos (4d8+4 PV)', 'Poder de paladino'],
    ['Poder de paladino'],
    ['Poder de paladino'],
    ['Golpe divino (+5d8)', 'Poder de paladino'],
    ['Cura pelas mãos (5d8+5 PV)', 'Poder de paladino'],
    ['Poder de paladino'],
    ['Poder de paladino', 'Vingador sagrado'],
  ],
  'Miragem': [
    ['Dança da Areia', 'Movimento Furtivo'],
    ['Poder de miragem'],
    ['Investida Acrobática', 'Poder de miragem'],
    ['Poder de miragem'],
    ['Cortina de Poeira', 'Poder de miragem'],
    ['Poder de miragem'],
    ['Guerrilheiro das Dunas', 'Poder de miragem'],
    ['Poder de miragem'],
    ['Mergulho Terrestre', 'Poder de miragem'],
    ['Poder de miragem'],
    ['Poder de miragem'],
    ['Poder de miragem'],
    ['Poder de miragem'],
    ['Poder de miragem'],
    ['Poder de miragem'],
    ['Poder de miragem'],
    ['Poder de miragem'],
    ['Poder de miragem'],
    ['Poder de miragem'],
    ['Corpo de Areia', 'Poder de miragem'],
  ],
  'Místico': [
    ['Afinidade Elemental', 'Ataque Elemental', 'Magias (1º círculo)'],
    ['Língua Primordial', 'Poder de místico'],
    ['Tradição Oral', 'Poder de místico'],
    ['Sexto Sentido', 'Poder de místico'],
    ['Magias (2º círculo)', 'Poder de místico'],
    ['Afinidade Evoluída', 'Poder de místico'],
    ['Poder de místico'],
    ['Poder de místico'],
    ['Magias (3º círculo)', 'Poder de místico'],
    ['Poder de místico'],
    ['Poder de místico'],
    ['Poder de místico'],
    ['Magias (4º círculo)', 'Poder de místico'],
    ['Poder de místico'],
    ['Poder de místico'],
    ['Poder de místico'],
    ['Magias (5º círculo)', 'Poder de místico'],
    ['Poder de místico'],
    ['Poder de místico'],
    ['Comunhão Suprema', 'Poder de místico'],
  ],
  'Samurai': [
    ['Arma Ancestral', 'Código do Samurai', 'Grito de Kiai'],
    ['Poder de samurai'],
    ['Olhar Assustador', 'Poder de samurai'],
    ['Poder de samurai'],
    ['Poder de samurai'],
    ['Poder de samurai'],
    ['Poder de samurai'],
    ['Poder de samurai'],
    ['Poder de samurai'],
    ['Arma Espiritual', 'Poder de samurai'],
    ['Poder de samurai'],
    ['Poder de samurai'],
    ['Poder de samurai'],
    ['Poder de samurai'],
    ['Poder de samurai'],
    ['Poder de samurai'],
    ['Poder de samurai'],
    ['Poder de samurai'],
    ['Poder de samurai'],
    ['Shogun', 'Poder de samurai'],
  ],
};

// Progressão de conjuradores. Fonte: Classes.pdf.
export const casterProgression: Record<string, CasterProgression> = {
  'Arcanista': {
    startingSpells: 3,
    spellsPerLevel: 1,
    circleAtLevel: { 1: 1, 5: 2, 9: 3, 13: 4, 17: 5 },
  },
  'Bardo': {
    startingSpells: 2,
    spellsPerLevel: 1,
    evenLevelsOnly: true,
    circleAtLevel: { 1: 1, 6: 2, 10: 3, 14: 4 },
  },
  'Clérigo': {
    startingSpells: 3,
    spellsPerLevel: 1,
    circleAtLevel: { 1: 1, 5: 2, 9: 3, 13: 4, 17: 5 },
  },
  'Druida': {
    startingSpells: 2,
    spellsPerLevel: 1,
    evenLevelsOnly: true,
    circleAtLevel: { 1: 1, 6: 2, 10: 3, 14: 4 },
  },
  'Místico': {
    startingSpells: 2,
    spellsPerLevel: 1,
    evenLevelsOnly: true,
    circleAtLevel: { 1: 1, 5: 2, 9: 3, 13: 4, 17: 5 },
  },
};
