export const classList = [
  'Arcanista', 'Bárbaro', 'Bardo', 'Bucaneiro', 'Caçador', 'Cavaleiro',
  'Clérigo', 'Druida', 'Guerreiro', 'Inventor', 'Ladino', 'Lutador', 'Miragem', 'Místico',
  'Nobre', 'Paladino', 'Samurai',
];

export const originData: Record<string, string[]> = {
  'Acólito':                   ['Cura', 'Religião', 'Vontade', 'Medicina', 'Membro da Igreja', 'Vontade de Ferro'],
  'Amigo dos Animais':         ['Adestramento', 'Cavalgar', 'Amigo Especial'],
  'Amnésico':                  ['Lembranças Graduais'],
  'Aristocrata':               ['Diplomacia', 'Enganação', 'Nobreza', 'Comandar', 'Sangue Azul'],
  'Artesão':                   ['Ofício', 'Vontade', 'Frutos do Trabalho', 'Sortudo'],
  'Artista':                   ['Atuação', 'Enganação', 'Atraente', 'Dom Artístico', 'Sortudo', 'Torcida'],
  'Assistente de Laboratório': ['Ofício (alquimia)', 'Misticismo', 'Esse Cheiro...', 'Venefício', 'Poder da Tormenta (à escolha)'],
  'Batedor':                   ['Furtividade', 'Percepção', 'Sobrevivência', 'À Prova de Tudo', 'Estilo de Disparo', 'Sentidos Aguçados'],
  'Capanga':                   ['Luta', 'Intimidação', 'Confissão', 'Poder de combate (à escolha)'],
  'Charlatão':                 ['Enganação', 'Jogatina', 'Alpinista Social', 'Aparência Inofensiva', 'Sortudo'],
  'Circense':                  ['Acrobacia', 'Atuação', 'Reflexos', 'Acrobático', 'Torcida', 'Truque de Mágica'],
  'Criminoso':                 ['Enganação', 'Furtividade', 'Ladinagem', 'Punguista', 'Venefício'],
  'Curandeiro':                ['Cura', 'Vontade', 'Medicina', 'Médico de Campo', 'Venefício'],
  'Eremita':                   ['Misticismo', 'Religião', 'Sobrevivência', 'Busca Interior', 'Lobo Solitário'],
  'Escravo':                   ['Atletismo', 'Fortitude', 'Furtividade', 'Desejo de Liberdade', 'Vitalidade'],
  'Estudioso':                 ['Conhecimento', 'Guerra', 'Misticismo', 'Aparência Inofensiva', 'Palpite Fundamentado'],
  'Fazendeiro':                ['Adestramento', 'Cavalgar', 'Ofício (fazendeiro)', 'Sobrevivência', 'Água no Feijão', 'Ginete'],
  'Forasteiro':                ['Cavalgar', 'Pilotagem', 'Sobrevivência', 'Cultura Exótica', 'Lobo Solitário'],
  'Gladiador':                 ['Atuação', 'Luta', 'Atraente', 'Pão e Circo', 'Torcida', 'Poder de combate (à escolha)'],
  'Guarda':                    ['Investigação', 'Luta', 'Percepção', 'Detetive', 'Investigador', 'Poder de combate (à escolha)'],
  'Herdeiro':                  ['Misticismo', 'Nobreza', 'Ofício', 'Comandar', 'Herança'],
  'Herói Camponês':            ['Adestramento', 'Ofício', 'Amigo dos Plebeus', 'Sortudo', 'Surto Heroico', 'Torcida'],
  'Marujo':                    ['Atletismo', 'Jogatina', 'Pilotagem', 'Acrobático', 'Passagem de Navio'],
  'Mateiro':                   ['Atletismo', 'Furtividade', 'Sobrevivência', 'Lobo Solitário', 'Sentidos Aguçados', 'Vendedor de Carcaças'],
  'Membro de Guilda':          ['Diplomacia', 'Enganação', 'Misticismo', 'Ofício', 'Foco em Perícia', 'Rede de Contatos'],
  'Mercador':                  ['Diplomacia', 'Intuição', 'Ofício', 'Negociação', 'Proficiência', 'Sortudo'],
  'Minerador':                 ['Atletismo', 'Fortitude', 'Ofício (minerador)', 'Ataque Poderoso', 'Escavador', 'Sentidos Aguçados'],
  'Nômade':                    ['Cavalgar', 'Pilotagem', 'Sobrevivência', 'Lobo Solitário', 'Mochileiro', 'Sentidos Aguçados'],
  'Pivete':                    ['Furtividade', 'Iniciativa', 'Ladinagem', 'Acrobático', 'Aparência Inofensiva', 'Quebra-Galho'],
  'Refugiado':                 ['Fortitude', 'Reflexos', 'Vontade', 'Estoico', 'Vontade de Ferro'],
  'Seguidor':                  ['Adestramento', 'Ofício', 'Antigo Mestre', 'Proficiência', 'Surto Heroico'],
  'Selvagem':                  ['Percepção', 'Reflexos', 'Sobrevivência', 'Lobo Solitário', 'Vida Rústica', 'Vitalidade'],
  'Soldado':                   ['Fortitude', 'Guerra', 'Luta', 'Pontaria', 'Influência Militar', 'Poder de combate (à escolha)'],
  'Taverneiro':                ['Diplomacia', 'Jogatina', 'Ofício (culinária)', 'Gororoba', 'Proficiência', 'Vitalidade'],
  'Trabalhador':               ['Atletismo', 'Fortitude', 'Atlético', 'Esforçado'],
  // Origens complementares (Complemento – Origens)
  'Aluno Irregular':           ['Misticismo', 'Vontade', 'Resistência Mágica', 'Ativação de Pergaminho'],
  'Filho de Svalas':           ['Conhecimento (Religioso)', 'Nobreza', 'Vontade', 'Bênção de Svalas'],
  'Filha de Moreania':         ['Adestramento', 'Sobrevivência', 'Companheiro Animal Pequeno'],
  'Indomável':                 ['Atletismo', 'Fortitude', 'Vontade de Ferro', 'Golpe Natural'],
  'Kami':                      ['Misticismo', 'Percepção', 'Vontade', 'Companheiro Kami'],
  'Malandragem de Ahlen':      ['Enganação', 'Furtividade', 'Ladinagem', 'Sortudo'],
  'Nativo de Midgard':         ['Atletismo', 'Fortitude', 'Sobrevivência', 'Adaptação Nórdica', 'Lobo Solitário'],
  'Retornado de Helheim':      ['Conhecimento (Plano Espiritual)', 'Fortitude', 'Vontade', 'Marca do Retorno', 'Memória de Além'],
  'Sobrevivente da Névoa':     ['Furtividade', 'Percepção', 'Vontade', 'Sentidos da Névoa', 'Resistência à Tormenta'],
};

export const originList = [
  'Acólito', 'Aluno Irregular', 'Amigo dos Animais', 'Amnésico', 'Aristocrata', 'Artesão',
  'Artista', 'Assistente de Laboratório', 'Batedor', 'Capanga', 'Charlatão',
  'Circense', 'Criminoso', 'Curandeiro', 'Eremita', 'Escravo', 'Estudioso',
  'Fazendeiro', 'Filha de Moreania', 'Filho de Svalas', 'Forasteiro', 'Gladiador',
  'Guarda', 'Herdeiro', 'Herói Camponês', 'Indomável', 'Kami',
  'Malandragem de Ahlen', 'Marujo', 'Mateiro', 'Membro de Guilda', 'Mercador',
  'Minerador', 'Nativo de Midgard', 'Nômade', 'Pivete', 'Refugiado',
  'Retornado de Helheim', 'Seguidor', 'Selvagem', 'Sobrevivente da Névoa',
  'Soldado', 'Taverneiro', 'Trabalhador',
];

export const deityList = [
  'A Sombra', 'Aharadak', 'Allihanna', 'Arsenal', 'Azgher', 'Hyninn', 'Kallyadranoch',
  'Khalmyr', 'Lena', 'Lin-Wu', 'Marah', 'Megalokk', 'Nimb', 'Oceano',
  'Sszzaas', 'Tanna-Toh', 'Tenebra', 'Thwor', 'Thyatis', 'Valkaria', 'Wynna',
];
