export interface CoCOccupationDef {
  id: string;
  name: string;
  /** e.g. "EDU×4" | "EDU×2 + APP×2" */
  skillPointsFormula: string;
  /** parsed coefficients for computation */
  formulaCoeffs: { attr: 'edu' | 'str' | 'dex' | 'app' | 'pow'; mult: number }[];
  creditRating: [number, number];
  /** Skill IDs from which occupation points must be spent (8 canonical skills) */
  occupationSkills: string[];
  /** Extra free-pick slots inside the occupation list ("any X skills") */
  freeSlots: number;
  era: ('1920s' | 'modern' | 'any')[];
}

function f(
  ...pairs: [attr: 'edu' | 'str' | 'dex' | 'app' | 'pow', mult: number][]
): { attr: 'edu' | 'str' | 'dex' | 'app' | 'pow'; mult: number }[] {
  return pairs.map(([attr, mult]) => ({ attr, mult }));
}

export const COC_OCCUPATIONS: CoCOccupationDef[] = [
  {
    id: 'academico',
    name: 'Acadêmico / Professor',
    skillPointsFormula: 'EDU×4',
    formulaCoeffs: f(['edu', 4]),
    creditRating: [20, 70],
    occupationSkills: ['antropologia', 'arqueologia', 'historia', 'usar-biblioteca', 'ocultismo', 'persuadir', 'psicologia', 'idioma-frances'],
    freeSlots: 1,
    era: ['any'],
  },
  {
    id: 'advogado',
    name: 'Advogado',
    skillPointsFormula: 'EDU×4',
    formulaCoeffs: f(['edu', 4]),
    creditRating: [30, 80],
    occupationSkills: ['contabilidade', 'direito', 'historia', 'intimidacao', 'usar-biblioteca', 'persuadir', 'psicologia', 'credito'],
    freeSlots: 1,
    era: ['any'],
  },
  {
    id: 'antiquario',
    name: 'Antiquário',
    skillPointsFormula: 'EDU×4',
    formulaCoeffs: f(['edu', 4]),
    creditRating: [30, 70],
    occupationSkills: ['avaliar', 'historia', 'usar-biblioteca', 'mundo-natural', 'ocultismo', 'persuadir', 'credito', 'idioma-frances'],
    freeSlots: 1,
    era: ['any'],
  },
  {
    id: 'artista',
    name: 'Artista',
    skillPointsFormula: 'EDU×2 + APP×2',
    formulaCoeffs: f(['edu', 2], ['app', 2]),
    creditRating: [9, 30],
    occupationSkills: ['arte-pintura', 'historia', 'psicologia', 'usar-biblioteca', 'idioma-frances', 'charme', 'escuta', 'credito'],
    freeSlots: 1,
    era: ['any'],
  },
  {
    id: 'atleta',
    name: 'Atleta',
    skillPointsFormula: 'EDU×2 + DES×2',
    formulaCoeffs: f(['edu', 2], ['dex', 2]),
    creditRating: [9, 70],
    occupationSkills: ['escalada', 'saltar', 'natacao', 'lutar-briga', 'primeiros-socorros', 'arremessar', 'furtividade', 'credito'],
    freeSlots: 1,
    era: ['any'],
  },
  {
    id: 'aventureiro',
    name: 'Aventureiro',
    skillPointsFormula: 'EDU×2 + DES×2',
    formulaCoeffs: f(['edu', 2], ['dex', 2]),
    creditRating: [8, 50],
    occupationSkills: ['escalada', 'lutar-briga', 'arma-fogo-pistola', 'primeiros-socorros', 'navegar', 'furtividade', 'sobrevivencia', 'credito'],
    freeSlots: 2,
    era: ['any'],
  },
  {
    id: 'cacador',
    name: 'Caçador',
    skillPointsFormula: 'EDU×2 + DES×2',
    formulaCoeffs: f(['edu', 2], ['dex', 2]),
    creditRating: [20, 50],
    occupationSkills: ['arma-fogo-rifle', 'rastrear', 'sobrevivencia', 'mundo-natural', 'escalada', 'primeiros-socorros', 'furtividade', 'credito'],
    freeSlots: 0,
    era: ['any'],
  },
  {
    id: 'cientista',
    name: 'Cientista',
    skillPointsFormula: 'EDU×4',
    formulaCoeffs: f(['edu', 4]),
    creditRating: [9, 35],
    occupationSkills: ['ciencia-fisica', 'ciencia-quimica', 'usar-biblioteca', 'historia', 'conserto-eletrico', 'psicologia', 'credito', 'ciencia-biologia'],
    freeSlots: 1,
    era: ['any'],
  },
  {
    id: 'clerigo',
    name: 'Clérigo / Padre',
    skillPointsFormula: 'EDU×4',
    formulaCoeffs: f(['edu', 4]),
    creditRating: [9, 60],
    occupationSkills: ['contabilidade', 'historia', 'usar-biblioteca', 'medicina', 'persuadir', 'psicologia', 'ocultismo', 'credito'],
    freeSlots: 1,
    era: ['any'],
  },
  {
    id: 'contador',
    name: 'Contador',
    skillPointsFormula: 'EDU×4',
    formulaCoeffs: f(['edu', 4]),
    creditRating: [30, 70],
    occupationSkills: ['contabilidade', 'direito', 'usar-biblioteca', 'psicologia', 'persuadir', 'labia', 'credito', 'avaliar'],
    freeSlots: 1,
    era: ['any'],
  },
  {
    id: 'criminoso',
    name: 'Criminoso',
    skillPointsFormula: 'EDU×2 + DES×2',
    formulaCoeffs: f(['edu', 2], ['dex', 2]),
    creditRating: [5, 65],
    occupationSkills: ['abrir-fechaduras', 'lutar-briga', 'labia', 'furtividade', 'intimidacao', 'arma-fogo-pistola', 'prestidigitacao', 'credito'],
    freeSlots: 1,
    era: ['any'],
  },
  {
    id: 'detetive',
    name: 'Detetive',
    skillPointsFormula: 'EDU×2 + DES×2',
    formulaCoeffs: f(['edu', 2], ['dex', 2]),
    creditRating: [20, 50],
    occupationSkills: ['pista', 'disfarce', 'intimidacao', 'direito', 'usar-biblioteca', 'psicologia', 'rastrear', 'credito'],
    freeSlots: 1,
    era: ['any'],
  },
  {
    id: 'detetive-particular',
    name: 'Detetive Particular',
    skillPointsFormula: 'EDU×2 + APP×2',
    formulaCoeffs: f(['edu', 2], ['app', 2]),
    creditRating: [9, 30],
    occupationSkills: ['pista', 'disfarce', 'psicologia', 'rastrear', 'usar-biblioteca', 'charme', 'persuadir', 'credito'],
    freeSlots: 1,
    era: ['any'],
  },
  {
    id: 'dilettante',
    name: 'Dilettante',
    skillPointsFormula: 'EDU×2 + APP×2',
    formulaCoeffs: f(['edu', 2], ['app', 2]),
    creditRating: [50, 99],
    occupationSkills: ['arte-pintura', 'cavalgar', 'charme', 'furtividade', 'historia', 'usar-biblioteca', 'percepcao', 'credito'],
    freeSlots: 2,
    era: ['any'],
  },
  {
    id: 'enfermeiro',
    name: 'Enfermeiro(a)',
    skillPointsFormula: 'EDU×4',
    formulaCoeffs: f(['edu', 4]),
    creditRating: [9, 30],
    occupationSkills: ['primeiros-socorros', 'medicina', 'psicologia', 'ciencia-biologia', 'usar-biblioteca', 'persuadir', 'escuta', 'credito'],
    freeSlots: 0,
    era: ['any'],
  },
  {
    id: 'escritor',
    name: 'Escritor / Editor',
    skillPointsFormula: 'EDU×4',
    formulaCoeffs: f(['edu', 4]),
    creditRating: [9, 30],
    occupationSkills: ['arte-escrita', 'historia', 'usar-biblioteca', 'ocultismo', 'psicologia', 'idioma-frances', 'charme', 'credito'],
    freeSlots: 1,
    era: ['any'],
  },
  {
    id: 'espiao',
    name: 'Espião(ã)',
    skillPointsFormula: 'EDU×2 + APP×2',
    formulaCoeffs: f(['edu', 2], ['app', 2]),
    creditRating: [20, 60],
    occupationSkills: ['disfarce', 'escuta', 'idioma-frances', 'furtividade', 'psicologia', 'arma-fogo-pistola', 'charme', 'credito'],
    freeSlots: 1,
    era: ['any'],
  },
  {
    id: 'estudante',
    name: 'Estudante',
    skillPointsFormula: 'EDU×4',
    formulaCoeffs: f(['edu', 4]),
    creditRating: [5, 40],
    occupationSkills: ['usar-biblioteca', 'historia', 'psicologia', 'idioma-frances', 'ciencia-biologia', 'escuta', 'percepcao', 'credito'],
    freeSlots: 2,
    era: ['any'],
  },
  {
    id: 'explorador',
    name: 'Explorador',
    skillPointsFormula: 'EDU×2 + STR×2',
    formulaCoeffs: f(['edu', 2], ['str', 2]),
    creditRating: [30, 60],
    occupationSkills: ['escalada', 'navegar', 'mundo-natural', 'rastrear', 'sobrevivencia', 'arma-fogo-rifle', 'historia', 'credito'],
    freeSlots: 1,
    era: ['any'],
  },
  {
    id: 'fazendeiro',
    name: 'Fazendeiro / Lavrador',
    skillPointsFormula: 'EDU×2 + STR×2',
    formulaCoeffs: f(['edu', 2], ['str', 2]),
    creditRating: [9, 30],
    occupationSkills: ['conserto-mecanico', 'lidar-animais', 'mundo-natural', 'primeiros-socorros', 'lutar-briga', 'rastrear', 'arma-fogo-rifle', 'credito'],
    freeSlots: 0,
    era: ['any'],
  },
  {
    id: 'fotografo',
    name: 'Fotógrafo / Jornalista',
    skillPointsFormula: 'EDU×4',
    formulaCoeffs: f(['edu', 4]),
    creditRating: [9, 30],
    occupationSkills: ['arte-fotografia', 'charme', 'psicologia', 'intimidacao', 'usar-biblioteca', 'persuadir', 'escuta', 'credito'],
    freeSlots: 1,
    era: ['any'],
  },
  {
    id: 'funcionario-governo',
    name: 'Funcionário Governamental',
    skillPointsFormula: 'EDU×4',
    formulaCoeffs: f(['edu', 4]),
    creditRating: [20, 40],
    occupationSkills: ['contabilidade', 'direito', 'usar-biblioteca', 'persuadir', 'psicologia', 'labia', 'pista', 'credito'],
    freeSlots: 1,
    era: ['any'],
  },
  {
    id: 'marinheiro',
    name: 'Marinheiro',
    skillPointsFormula: 'EDU×2 + DES×2',
    formulaCoeffs: f(['edu', 2], ['dex', 2]),
    creditRating: [9, 30],
    occupationSkills: ['conserto-mecanico', 'lutar-briga', 'navegar', 'natacao', 'escalada', 'arremessar', 'sobrevivencia', 'credito'],
    freeSlots: 0,
    era: ['any'],
  },
  {
    id: 'medico',
    name: 'Médico',
    skillPointsFormula: 'EDU×4',
    formulaCoeffs: f(['edu', 4]),
    creditRating: [30, 80],
    occupationSkills: ['primeiros-socorros', 'medicina', 'psicanalise', 'psicologia', 'ciencia-biologia', 'usar-biblioteca', 'persuadir', 'credito'],
    freeSlots: 0,
    era: ['any'],
  },
  {
    id: 'mecanico',
    name: 'Mecânico / Engenheiro',
    skillPointsFormula: 'EDU×4',
    formulaCoeffs: f(['edu', 4]),
    creditRating: [9, 30],
    occupationSkills: ['conserto-mecanico', 'conserto-eletrico', 'operar-maquinaria', 'conduzir-auto', 'ciencia-fisica', 'usar-biblioteca', 'lutar-briga', 'credito'],
    freeSlots: 0,
    era: ['any'],
  },
  {
    id: 'militar',
    name: 'Militar / Oficial',
    skillPointsFormula: 'EDU×2 + DES×2',
    formulaCoeffs: f(['edu', 2], ['dex', 2]),
    creditRating: [20, 70],
    occupationSkills: ['arma-fogo-pistola', 'arma-fogo-rifle', 'lutar-briga', 'primeiros-socorros', 'intimidacao', 'mapeamento', 'sobrevivencia', 'credito'],
    freeSlots: 1,
    era: ['any'],
  },
  {
    id: 'motorista',
    name: 'Motorista / Chauffeur',
    skillPointsFormula: 'EDU×2 + DES×2',
    formulaCoeffs: f(['edu', 2], ['dex', 2]),
    creditRating: [9, 30],
    occupationSkills: ['conserto-mecanico', 'conduzir-auto', 'furtividade', 'escuta', 'navegar', 'arma-fogo-pistola', 'lutar-briga', 'credito'],
    freeSlots: 0,
    era: ['any'],
  },
  {
    id: 'musico',
    name: 'Músico',
    skillPointsFormula: 'EDU×2 + APP×2',
    formulaCoeffs: f(['edu', 2], ['app', 2]),
    creditRating: [9, 30],
    occupationSkills: ['arte-musica', 'arte-canto', 'charme', 'escuta', 'psicologia', 'historia', 'idioma-frances', 'credito'],
    freeSlots: 1,
    era: ['any'],
  },
  {
    id: 'ocultista',
    name: 'Ocultista',
    skillPointsFormula: 'EDU×4',
    formulaCoeffs: f(['edu', 4]),
    creditRating: [9, 65],
    occupationSkills: ['antropologia', 'historia', 'usar-biblioteca', 'ocultismo', 'psicologia', 'ciencia-fisica', 'idioma-latim', 'credito'],
    freeSlots: 1,
    era: ['any'],
  },
  {
    id: 'parapsicólogo',
    name: 'Parapsicólogo',
    skillPointsFormula: 'EDU×4',
    formulaCoeffs: f(['edu', 4]),
    creditRating: [9, 30],
    occupationSkills: ['ocultismo', 'psicologia', 'usar-biblioteca', 'historia', 'percepcao', 'persuadir', 'escuta', 'credito'],
    freeSlots: 1,
    era: ['any'],
  },
  {
    id: 'piloto',
    name: 'Piloto',
    skillPointsFormula: 'EDU×2 + DES×2',
    formulaCoeffs: f(['edu', 2], ['dex', 2]),
    creditRating: [20, 50],
    occupationSkills: ['pilotar-aviao', 'conduzir-auto', 'conserto-mecanico', 'navegar', 'meteorologia', 'pista', 'arma-fogo-pistola', 'credito'],
    freeSlots: 0,
    era: ['any'],
  },
  {
    id: 'policial',
    name: 'Policial / Detetive',
    skillPointsFormula: 'EDU×2 + DES×2',
    formulaCoeffs: f(['edu', 2], ['dex', 2]),
    creditRating: [9, 30],
    occupationSkills: ['pista', 'lutar-briga', 'arma-fogo-pistola', 'intimidacao', 'direito', 'psicologia', 'conduzir-auto', 'credito'],
    freeSlots: 1,
    era: ['any'],
  },
  {
    id: 'psicologo',
    name: 'Psicólogo / Psiquiatra',
    skillPointsFormula: 'EDU×4',
    formulaCoeffs: f(['edu', 4]),
    creditRating: [30, 70],
    occupationSkills: ['psicanalise', 'psicologia', 'medicina', 'usar-biblioteca', 'escuta', 'persuadir', 'historia', 'credito'],
    freeSlots: 0,
    era: ['any'],
  },
  {
    id: 'trabalhador',
    name: 'Trabalhador / Operário',
    skillPointsFormula: 'EDU×2 + STR×2',
    formulaCoeffs: f(['edu', 2], ['str', 2]),
    creditRating: [9, 30],
    occupationSkills: ['conserto-mecanico', 'operar-maquinaria', 'lutar-briga', 'escalada', 'primeiros-socorros', 'intimidacao', 'arremessar', 'credito'],
    freeSlots: 0,
    era: ['any'],
  },
  {
    id: 'vigarista',
    name: 'Vigarista',
    skillPointsFormula: 'EDU×2 + APP×2',
    formulaCoeffs: f(['edu', 2], ['app', 2]),
    creditRating: [10, 65],
    occupationSkills: ['charme', 'labia', 'disfarce', 'escuta', 'psicologia', 'furtividade', 'prestidigitacao', 'credito'],
    freeSlots: 1,
    era: ['any'],
  },
  // ── Específicas dos Anos 1920 ────────────────────────────────────────────
  {
    id: 'bootlegger',
    name: 'Contrabandista (Bootlegger)',
    skillPointsFormula: 'EDU×2 + DES×2',
    formulaCoeffs: f(['edu', 2], ['dex', 2]),
    creditRating: [5, 75],
    occupationSkills: ['conduzir-auto', 'lutar-briga', 'arma-fogo-pistola', 'furtividade', 'labia', 'navegar', 'intimidacao', 'credito'],
    freeSlots: 0,
    era: ['1920s'],
  },
  {
    id: 'reporter-1920s',
    name: 'Repórter (Anos 1920)',
    skillPointsFormula: 'EDU×4',
    formulaCoeffs: f(['edu', 4]),
    creditRating: [9, 30],
    occupationSkills: ['arte-fotografia', 'pista', 'historia', 'usar-biblioteca', 'persuadir', 'psicologia', 'escuta', 'credito'],
    freeSlots: 1,
    era: ['1920s'],
  },
  // ── Específicas da Era Moderna ────────────────────────────────────────────
  {
    id: 'hacker',
    name: 'Hacker / Analista de TI',
    skillPointsFormula: 'EDU×4',
    formulaCoeffs: f(['edu', 4]),
    creditRating: [9, 30],
    occupationSkills: ['computacao', 'eletronica', 'usar-biblioteca', 'ciencia-matematica', 'conserto-eletrico', 'psicologia', 'labia', 'credito'],
    freeSlots: 0,
    era: ['modern'],
  },
  {
    id: 'profissional-saude',
    name: 'Profissional de Saúde',
    skillPointsFormula: 'EDU×4',
    formulaCoeffs: f(['edu', 4]),
    creditRating: [20, 45],
    occupationSkills: ['primeiros-socorros', 'medicina', 'psicologia', 'persuadir', 'usar-biblioteca', 'computacao', 'conduzir-auto', 'credito'],
    freeSlots: 0,
    era: ['modern'],
  },
];

export function getOccupationById(id: string): CoCOccupationDef | undefined {
  return COC_OCCUPATIONS.find(o => o.id === id);
}

export function getOccupationsForEra(era: '1920s' | 'modern'): CoCOccupationDef[] {
  return COC_OCCUPATIONS.filter(o =>
    o.era.includes('any') || o.era.includes(era),
  );
}

export function calcOccupationSkillPoints(
  occ: CoCOccupationDef,
  attrs: { edu: number; str: number; dex: number; app: number; pow: number },
): number {
  return occ.formulaCoeffs.reduce((sum, { attr, mult }) => sum + (attrs[attr] ?? 0) * mult, 0);
}
